[versions]
agp = "9.1.1"
android-compileSdk = "37"
android-minSdk = "23"
android-targetSdk = "37"
compose = "1.12.0"
java = "21"
kotlin = "2.4.20"
ktlint = "1.8.0"
log4k-demo = "1.0.0"
mockk = "1.14.11"
slf4j = "2.0.19"

[libraries]
androidx-activity-compose = "androidx.activity:activity-compose:1.13.0"
compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose" }
compose-components-ui-tooling-preview = { module = "org.jetbrains.compose.components:components-ui-tooling-preview", version.ref = "compose" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose" }
compose-material = { module = "org.jetbrains.compose.material:material", version.ref = "compose" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose" }
kotlin-wrappers = "org.jetbrains.kotlin-wrappers:kotlin-node:2026.8.0-24.12.4"
kotlinx-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.8.0"
kotlinx-io = "org.jetbrains.kotlinx:kotlinx-io-core:0.9.1"
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-hotReload = "org.jetbrains.compose.hot-reload:1.2.0"
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose" }
dokka = "org.jetbrains.dokka:2.2.0"
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
maven-publish = "com.vanniktech.maven.publish:0.37.0"
spotless = "com.diffplug.spotless:8.9.0"
versions = "io.github.ben-manes.versions:0.59.0"
